headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/mattkundo/My Drive (mattkundo@mattkundodigitalmarketing.com)/02_Clients/Active_Clients/BioPic_Studios/DIY-Editor-Landing-Page"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "https://custom-slideshows.biopicstudios.com/images/*"
to = "/images/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://celebration-slideshows.biopicstudios.com/images/*"
to = "/images/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://memorial-slideshows.biopicstudios.com/images/*"
to = "/images/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/privacy"
to = "https://biopicstudios.com/privacy"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/terms"
to = "https://biopicstudios.com/terms"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://custom-slideshows.biopicstudios.com/"
to = "/custom-slideshow.html"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://celebration-slideshows.biopicstudios.com/"
to = "/celebration-events.html"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://memorial-slideshows.biopicstudios.com/"
to = "/memorial-tribute.html"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]